# Generated by Django 3.0.2 on 2020-01-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT ITEM', max_length=500)),
                ('description', models.CharField(default='DEFAULT DESC', max_length=500)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
