# Generated by Django 3.0.2 on 2020-01-09 07:41

from django.db import migrations
from django.apps import apps

def generate_rooms(apps, schema_editor):
    Room = apps.get_model('adventure', 'Room')

    Room.objects.all().delete()

    # Roads
    p_dirt_path = Room(title="Dirt Path", description="Easy going path to a variety of adventures")
    p_mushroom_road = Room(title="Mushroom Road", description="The road to meet Mario")
    p_desert_path = Room(title="Desert Path", description="Prepare yourself to see the wonders of Shurima")
    p_marvel_road = Room(title="Marvel Road", description="The path to lead to your superhuman dreams")
    p_imagination_road = Room(title="Randomizer Road", description="A road that twists and turns beyond the will of fate")
    p_borg_path = Room(title="Borg Path", description="A path headed down destruction adn chaos")

    roads = [p_dirt_path, p_borg_path, p_desert_path, p_imagination_road, p_marvel_road, p_mushroom_road]
    for r in roads: r.save()

    # Shurima Rooms
    r_floating_pyramids = Room(title="Floating Pyramids", description="Pyramids sitting high above the desert in Shurima")
    r_targon = Room(title="Mt. Targon", description="The desolate mountain with the highest peak, Targon")
    r_moutain_pass = Room(title="Mountain Pass", description="Mountain pass used to cross the boarder, blocked with a key locked gate")
    r_nefaras_necrocalis = Room(title="Nefara's Necrocalis", description="Hut laid out near the cemetary, used for Necromancy training")
    r_fyron_flat = Room(title="Fyron's Salt Flat", description="House belonging to Fyron the Mage, imbued with magic and made of salt")
    r_shurima_lake = Room(title="Lake Shurima", description="Lake surround most of Shurima, the waters shift from shallow to deep very quickly")
    r_velocatronic = Room(title="Velocatronic Rail Station", description="Run down station that used to house the greatest train known to Shurima")
    r_voodou = Room(title="Voodou Lands", description="Land owned by the Farmers of Shurima, plenty of desert fruit around to eat")
    r_zayite_complex = Room(title="Zayite Complex", description="School specializing in life studies, and basic magics")
    r_shurima = Room(title="Shurima", description="The Heavenly Kingdom of Shurima")
    r_azirs_palace = Room(title="Azir's Palace", description="Grand Palace belonging to a descendant of Shurima")
    r_royal_palace = Room(title="Royal Palace", description="Palace used by the King of Shurima")
    r_water_gate = Room(title="Water Gate", description="Gate nested near the edge of the lake, to prevent flooding and the releasing of monstrous sea creatures")
    r_tempest_forest = Room(title="Tempest Forest", description="Forest of cacti and high winds")
    r_centralis = Room(title="Centralis", description="Shurima's neighboring Kingdom, home to the mighty ")
    r_holy_temple = Room(title="Holy Temple", description="A place to worship Shurima")
    r_pykes_grave = Room(title="Pyke's Grave", description="The burial spot of the Pirate drowned in sand")
    r_nasus_statue = Room(title="Nasus' Statue", description="Statue of the first descendant of Nasus")

    shurima = [r_nasus_statue, r_pykes_grave, r_holy_temple, r_centralis, r_azirs_palace, r_floating_pyramids, r_moutain_pass, r_nefaras_necrocalis, r_royal_palace, r_shurima_lake, r_shurima, r_velocatronic, r_voodou, r_water_gate, r_zayite_complex, r_tempest_forest, r_targon, r_fyron_flat]
    for n in shurima: n.save()

    # Marvel Rooms
    r_adamantium = Room(title = "Adamantium Room", description = """There seem to be claw like slashes all over the room!""")
    r_web = Room(title = "Web Room", description = """There are sticky webs all over this room.""")
    r_stark = Room(title = "Stark's Room", description = """There are vast amounts of electronics all over this room.""")
    r_pitch_black = Room(title = "Pitch Black", description = """Silence and darkness. You can't see anything in this room.""")
    r_science = Room(title = "Science Room", description = """It looks as though a monster tore out of this room.""")
    r_skull = Room(title = "The Skull Room", description = """Guns and amo everywhere. There is a picture of a death's head skull on the wall.""")
    r_cerebro = Room(title = "Cerebro", description = """There is a weird helmet in the middle of this round room. Its like we are in a ball.""")
    r_rock = Room(title = "The Rock", description = """Everywhere you look things are made of rock.""")
    r_bullseye = Room(title = "The Bullseye Room", description = """Hanging all around the room are targets that have been hit dead in the bullseye.""")
    r_tourch = Room(title = "Tourch", description = """Everything is on fire.""")
    r_ice = Room(title = "Ice", description = """Its so cold.""")
    r_small = Room(title = "Small Room", description = """Everything in here is so tiny. Like it was made for ants.""")
    r_aquarium = Room(title = "Aquarium", description = """All of the walls are fish tanks. There seems to be an entrance through the floor to the tank.""")
    r_lightning = Room(title = "Lightning", description = """This room seems to be charged with electricity. Don't touch the walls.""")
    r_dead_pool = Room(title = "Deadpool's Room", description = """There are little deadpool figurines everywhere. They all look to be dying though.""")
    r_hawk = Room(title = "Hawk Room", description = """There is a perch in the corner of the room.""")
    r_america = Room(title = "American Room", description = """Captain America stuff is everywhere.""")
    r_smash = Room(title = "Smash Room", description = """You can see several Hulk shirts ripped apart. All the little Hulk figurines have been smashed into little bitty peaces. """)
    
    places = [r_adamantium, r_america, r_aquarium, r_bullseye, r_cerebro, r_dead_pool, r_hawk, r_ice, r_lightning, r_pitch_black, r_rock, r_science, r_skull, r_small, r_smash, r_stark, r_tourch, r_web]
    for b in places: b.save()

    # Randomized Rooms
    r_suarward_dining = Room(title = "Suarward Dining", description = "Large, square dining room has mismatched wooden furniture.  The seating is cushioned.  The floor is stone. Overall has a quaint atmosphere.")
    r_talltail_chambers = Room(title = "TallTail Chambers", description = "Small, rectangular bedroom with wooden funiture. Among the first things one notices walking in is muddy footprints on the floor.")
    r_starStrike_sanctuary = Room(title = 'Starstrike Sanctuary', description = " This cramped, rectangular office has mismatched wooden, metal, and glass furniture, Upon entering one notices light from the heavens")
    r_grandwing_saloon = Room(title = "Grandwing Saloon", description = "Cramped, square, dim lit saloon. Broken glass covers the floor. There is a thick haze of smoke upon entering. Among the first things one notices walking in are a conspicuous stain on the floor")
    r_outcast_den = Room(title = "Outcast Den", description = "Large, L-shaped bathroom screams death. Leave Quickly!")
    r_starfall_hideout = Room(title = "Starfall Hideout", description = "Light is provided by wall lamps and a ceiling light. Among the first things one notices walking in are glitter footprints on the floor and a collection of action figures.")
    r_lightstorm_harbor = Room(title = "Lightstorm Harbor", description = "Among the first things one notices walking in is photographs on the wall. Long ago this was a sailors palace ")
    r_feather_nest = Room(title = "Feather Nest", description= "A large, square bedroom. The floor is layered with shedded feathers. The first thing one notices upon entering is a broken clock on the wall")
    r_coldwar_hideaway = Room(title = "Coldwar Hideaway", description= "The room is done in colors that remind you of Halloween and overall has a rustic look to it.  Among the first things one notices walking in are a crumpled paper")
    r_shadow_burrow = Room(title = "Shadow Burrow", description= "Cold, and cluttered with spell books. Upon entering one feels a draft come from the window that chills the soul")
    r_miracle_dungeon = Room(title = "Miracle Dungeon", description= "This large kitchen is magical. Powered by one's own imagination")
    r_skullblade_cave = Room(title = "skullblade_cave", description= "An average-sized cave, dark and mysterious. Sounds of flowing water come from deep within. Among entering bats fly out from everywhere.")
    r_thorn_nest = Room(title = "Thorn Nest", description= "Cramped office with matching wooden furniture. The room is done is such way it reminds one of a thorny nest")
    r_archkeep_sanctuary = Room(title = "Archkeep Sanctuary", description= "This spacious, bathroom is done in bold colors and overall has a quaint atmosphere.  Among the first things one notices walking in are a collection of knickknacks and many cosmetics strewn on the counter.")
    r_skyspell_haven = Room(title = "Skyspell Haven", description= "Vintage theme in murky colors and overall has a retro look to it.  Among the first things one notices walking in is a barn star on the wall.")
    r_flower_retreat = Room(title = "Flower Retreat", description= "A mystical garden, that is home to many fairies, but beware the dragons below")
    r_blitz_cover = Room(title = "Blitz Cover", description= "Underground, yet well lit. Blitz Cover is a reminder of safety in these parts")
    r_mystery_lair = Room(title = "Mystery Lair", description= "The room of deja vu, beware!")

    places = [r_suarward_dining, r_talltail_chambers, r_starStrike_sanctuary, r_grandwing_saloon, r_outcast_den, r_starfall_hideout, r_lightstorm_harbor, r_feather_nest, r_coldwar_hideaway, r_shadow_burrow, r_miracle_dungeon, r_skullblade_cave, r_thorn_nest, r_archkeep_sanctuary, r_skyspell_haven, r_flower_retreat, r_blitz_cover, r_mystery_lair]
    for x in places: x.save()

    # Mushroom Kingdom rooms
    r_gardner = Room(title="Gardners Garden", description="""This garden has grown the most lavish fruits and vegetables on the planet, look around you for fruits and vegetables.""")
    r_tomb = Room(title="The Kings Tomb", description="""You've found the long-lost Kings Tomb! Press C to loot the tomb.""")
    r_princess_peach_castle = Room(title="Princess Peach castle", description="""You've arrived to Princess Peach Castle! See if she has anything for you.""")
    r_bowsers_dungeon = Room(title="Bowsers Dungeon", description="""You're in Bowsers Dungeon, get what you can and get out of there!""")
    r_toad_town = Room(title="Toad Town", description="""Toad town is iconic, for housing some of the worlds biggest superstars. Look around and you might see Mario!""")
    r_bonies_cabin = Room(title="Bonies Cabin", description="""Bonie welcomed you inside, for food.""")
    r_goodnights_theatre = Room(title="Goodnights Theatre", description="""Shhhh! The show is about to start.""")
    r_yoshis_yoga_palace = Room(title="Yoshis Yoga Palace", description="""Sit down, close your eyes and find your inter zen.""")
    r_sarasaland = Room(title="Sarasaland", description="""Queen Daisy has been awaiting you're arrival, check what you can do for her.""")
    r_bowsers_kingdom = Room(title="Bowsers Kingdom", description="""Watch youself, you might be standing on lava!""")
    r_warios_woods = Room(title="Warios Woods", description="""Warios Woods has plenty of organic resources, pack up what you can and head to the market!""")
    r_rosalinas_land = Room(title="Rosalinas Land", description="""You've found the long-lost land of Princess Rosalina! The Lumas have left everything! Where could they be?""")
    r_koopalings_shack = Room(title="Kooplings Shack", description="""find a bed and get some rest.""")
    r_lumas_village = Room(title="Lumas Village", description="""Lumas village is known for its amazing sky at night, and great tradesmen. See if anyone wants to trade anything.""")
    r_toads_boat = Room(title="Toads Boat", description="""Toad said he'd take you to a special Island. Do you want to go?""")
    r_toads_island = Room(title="Toads Island", description="""See what the people here have to offer.""")
    r_marios_palace = Room(title="Marios Palace", description="""You've been selected to explore Marios palace.""")
    
    marios_world = [r_gardner,r_tomb,r_princess_peach_castle, r_bowsers_dungeon,r_toad_town,r_bonies_cabin, r_goodnights_theatre,r_yoshis_yoga_palace, r_sarasaland,r_bowsers_kingdom,r_warios_woods, r_rosalinas_land,r_koopalings_shack,r_lumas_village, r_toads_boat,r_toads_island,r_marios_palace]
    for r in marios_world: r.save()

    # The Borg Rooms
    r_borg = Room(title="The Borg", description="""Prepare to be assimilated! Resistance is futile!""")
    r_enterprise = Room(title="The Enterprise", description="""Space: the final frontier. Boldy go!""")
    r_vulcan = Room(title="Planet Vulcan", description="""Live long and prosper. Just don't get emotional about it.""")
    r_replicator = Room(title="The Replicator Room", description="""Order what you like. Picard recommneds: Tea, Earl Grey, hot!""")
    r_alpha_quadrant = Room(title="Alpha quadrant", description="""Ready to see the neighborhood? Make it so!""")
    r_transporter = Room(title="The Transporter Room", description="""If things get freaky down there, just call out: Beam me up, Scotty! When you are ready to go down just call out 'Engage!'""")
    r_stranded = Room(title="Stranded on Unknown Planet", description="""Did I tell you the one about Darmok and Jalad at Tanagra?""")
    r_holodeck = Room(title="The Holodeck", description="""Think of your wildest fantasy, and ypu're there. Try not to run into the walls. It can be a rude awakening.""")
    r_tribble = Room(title="The Tribble Room", description="""The Trouble with Tribbles? Those cute little furry things? Why, they're no tribble a'tal.""")
    r_romulan = Room(title="Romulan Warbird", description="""Get ready for battle! Death to the Cardassians!""")
    r_shore_leave = Room(title="Shore Leave", description="""If you see Alice chasing a White Rabbit, tell her he went for a cup of tea.""")
    r_earth = Room(title="Planet Earth", description="""Earth inhabitants: Ugly bags of mostly water.""")
    r_klingon = Room(title="Klingon Home Planet", description="""Get ready for some Gok. Best when the worms are alive and wriggling. Wash it down with a warm glass of Blood Wine.""")
    r_jefferies_tube = Room(title="Jefferies Tube", description="""Just keep your head down and crawl low. Don't touch that pipe. It might be scaldingly hot. And if you touch the high power line, don't worry--no pain with instant death.""")
    r_delta_quadrant = Room(title="Delta Quadrant", description="""Thought you were going on a short test run? No problem. Just forty years back to the Alpha Quadrant. Talk about a long distance Voyager.""")
    r_pon_farr = Room(title="Pon Farr", description="""Thought you could just forget about it and it would go away? No way. Time to pair up my mate. May as well have some wild fun.""")
    r_neutral_zone = Room(title="The Neutral Zone", description="""Get out as quickly as you can. Breaking the treaty of the Neutral Zone is highly offensive. Watch out for that Romulan War bird. It's gunning for ya""")
    r_bajoran_wormhole = Room(title="Bajoran Wormhole", description="""Thought the war on Bajora with the Cardassians was bad? Well, enjoy getting sucked into this Bajoran Wormhole. Maybe you will luck out and get to the other side and only have to face the Dominion.""")
    r_baryon_sweep = Room(title="Baryon Sweep", description="""Such unfortunate timing my friend. You have managed to beam aboard a vessal undergoing a Baryon Sweep. Yes, any organic living matter will be neutralized when the Baryon Sweep gets to its position onboard the craft. Sure hope you are not organic.""")
    r_cardassia_prime = Room(title="Cardassia Prime", description="""Lucky you. Very Festive times now on Cardassia Prime. Everyone is celebrating making war on Bajor. You are Bjoran you say? Uh oh!""")
    
    borg_hoard = [r_borg, r_enterprise, r_vulcan, r_replicator, r_alpha_quadrant, r_transporter, r_stranded, r_holodeck, r_tribble, r_romulan, r_shore_leave, r_earth, r_klingon, r_jefferies_tube, r_delta_quadrant, r_pon_farr, r_neutral_zone, r_bajoran_wormhole, r_baryon_sweep, r_cardassia_prime ]
    for b in borg_hoard: b.save()

    # Connecting the rooms and the roads
    import random

    directions = ["n","s","e","w"]

    rndnum = randint(1, 16)
    rnddir = random.choice(directions)
    
    p_dirt_path.connect_rooms(p_imagination_road, "n")
    p_dirt_path.connect_rooms(p_desert_path, "s")
    p_dirt_path.connect_rooms(p_borg_path, "e")
    p_dirt_path.connect_rooms(p_mushroom_road, "w")

    borg_hoard = borg_hoard[rndnum:] + borg_hoard[:rndnum]
    marios_world = marios_world[rndnum:] + marios_world[:rndnum]
    shurima = shurima[rndnum:] + shurima[:rndnum]
    places = places[rndnum:] + places[:rndnum]

    p_imagination_road.connect_rooms(places[0], "n")




class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_rooms),
    ]
